Repository hmcts/juror-shared-infrastructure, pull requests merged in 2024-02, with the labels that each got.

#18 create AD groups for Juror Admin Keyvault
  key-vault.tf
  locals.tf
Labels: destroy

#19 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: no-changes

#20 initial test of generating secrets
  locals.tf
  secrets.tf
Labels: add-or-update

#21 Jm 5903
  locals.tf
  secrets.tf
Labels: destroy

#23 Jm 5903
  locals.tf
  secrets.tf
Labels: destroy

#24 Jm 5903
  locals.tf
Labels: add-or-update

#25 renamed exe secret
  locals.tf
Labels: destroy

#27 Jm 5533
  dbmigrationvm.tf
  install-docker.sh
  provider.tf
Labels: add-or-update

#28 reintroduce nonprod mapping
  dbmigrationvm.tf
Labels: add-or-update

#29 correct typo
  dbmigrationvm.tf
Labels: add-or-update

#30 try other subscription variable
  dbmigrationvm.tf
  variables.tf
Labels: add-or-update

#31 change sku
  dbmigrationvm.tf
Labels: add-or-update

#32 try changing sku
  dbmigrationvm.tf
Labels: add-or-update

#33 try changing offer etc
  dbmigrationvm.tf
Labels: add-or-update

#34 tidy up
  dbmigrationvm.tf
Labels: destroy

#36 feat: set env vars from key vault
  dbmigrationvm.tf
  locals.tf
  set-env-variables.sh
Labels: add-or-update
